packages:
  - 'packages/*'
  - 'packages/shared/*'
  - 'packages/infrastructure/*'
  - 'apps/*'

autoInstallPeers: true
allowBuilds:
  '@parcel/watcher': true
  less: false
  nx: true
  unrs-resolver: true
  '@nestjs/core': false
  esbuild: false
  '@swc/core': true
  '@scarf/scarf': false
