import {HttpStatus} from '@b2b-saas-starter-kit/contracts'

/** Application error `code` → HTTP status. Unmapped codes default to 409 in the kit filter. */
export const codedErrorHttpStatuses: Readonly<Record<string, number>> = {
  INSUFFICIENT_PERMISSION: HttpStatus.FORBIDDEN,
  USER_NOT_FOUND: HttpStatus.NOT_FOUND,
  OWNER_USER_NOT_FOUND: HttpStatus.NOT_FOUND,
  USER_EMAIL_TAKEN: HttpStatus.CONFLICT,
  INVALID_CREDENTIALS: HttpStatus.UNAUTHORIZED,
  USER_SUSPENDED: HttpStatus.FORBIDDEN,
  INVALID_PASSWORD: HttpStatus.BAD_REQUEST,
  PASSWORD_ALREADY_SET: HttpStatus.CONFLICT,
  INVALID_REFRESH_TOKEN: HttpStatus.UNAUTHORIZED,
  INVALID_RESET_TOKEN: HttpStatus.BAD_REQUEST,
  ACTIVE_MEMBERSHIP_REQUIRED: HttpStatus.FORBIDDEN,
  CANNOT_ASSIGN_OWNER_ROLE: HttpStatus.FORBIDDEN,
  LAST_OWNER_REQUIRED: HttpStatus.CONFLICT,
  INVITATION_ALREADY_PENDING: HttpStatus.CONFLICT,
  MEMBERSHIP_ALREADY_EXISTS: HttpStatus.CONFLICT,
  INVALID_INVITATION_TOKEN: HttpStatus.BAD_REQUEST,
  INVITATION_REGISTRATION_REQUIRED: HttpStatus.BAD_REQUEST,
  MEMBERSHIP_NOT_FOUND: HttpStatus.NOT_FOUND,
  TENANT_NOT_FOUND: HttpStatus.NOT_FOUND,
  ROLE_NOT_FOUND: HttpStatus.NOT_FOUND,
  ROLE_NAME_TAKEN: HttpStatus.CONFLICT,
  ROLE_IN_USE: HttpStatus.CONFLICT,
  SYSTEM_ROLE_IMMUTABLE: HttpStatus.FORBIDDEN,
  RESERVED_ROLE_NAME: HttpStatus.CONFLICT,
}
